name: Build

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macOS:
    env:
      PACKAGE_VER: undefined
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test
      - name: Build a release version for macOS
        run: cargo build --release
      - name: Install Windows target
        run: rustup target add x86_64-pc-windows-gnu
      - name: Install MinGW
        run: brew install mingw-w64
      - name: Install Linux target
        run: |
          rustup target add x86_64-unknown-linux-musl
          brew tap filosottile/musl-cross
          brew install musl-cross
      - name: Release version for Windows
        run: cargo build --release --target x86_64-pc-windows-gnu
      - name: Release version for Linux
        run: cargo build --release --target x86_64-unknown-linux-musl
      - name: Rename build artifacts
        run: |
          mv target/release/mclint target/release/mclint-mac
          mv target/x86_64-pc-windows-gnu/release/mclint.exe target/x86_64-pc-windows-gnu/release/mclint-win.exe
          mv target/x86_64-unknown-linux-musl/release/mclint target/x86_64-unknown-linux-musl/release/mclint-lin
      - name: Upload built artifact
        uses: actions/upload-artifact@v2
        with:
          name: macOS
          path: target/release/mclint
      - name: Automatic upload to latest alpha
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Build"
          files: |
            target/release/mclint-mac
            target/x86_64-pc-windows-gnu/release/mclint-win.exe
            target/x86_64-unknown-linux-musl/release/mclint-lin

  build-Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Also build a release version
        run: cargo build --release --verbose

      - name: Upload built artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: target/release/mclint.exe

  build-Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Also build a release version
        run: cargo build --release --verbose

      - name: Upload built artifact
        uses: actions/upload-artifact@v2
        with:
          name: Linux
          path: target/release/mclint